<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ThreadDesk.Infrastructure\ThreadDesk.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\ThreadDesk.Core\ThreadDesk.Core.csproj" />
  </ItemGroup>
</Project>